# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='typeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Classify'),
        ),
    ]
